// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOw8MOCw3DRvZ2LfqFNd-8J82ISiLR7zg',
    appId: '1:884285337726:web:fd55e4ad515d1b73aa682f',
    messagingSenderId: '884285337726',
    projectId: 'gestorcobranza-721b0',
    authDomain: 'gestorcobranza-721b0.firebaseapp.com',
    storageBucket: 'gestorcobranza-721b0.appspot.com',
    measurementId: 'G-JBRCME2RWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Qq5kd22iUcbrDbIl9_XDEA2kQAgRFgU',
    appId: '1:884285337726:android:7459ea09b4c247cbaa682f',
    messagingSenderId: '884285337726',
    projectId: 'gestorcobranza-721b0',
    storageBucket: 'gestorcobranza-721b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2MtantE_FkjVf6Od0cB7N1Z50Ca_lIM0',
    appId: '1:884285337726:ios:6eee20e0f2233697aa682f',
    messagingSenderId: '884285337726',
    projectId: 'gestorcobranza-721b0',
    storageBucket: 'gestorcobranza-721b0.appspot.com',
    androidClientId: '884285337726-c83mr8v19rha29mdjfu1hikdfrcrcbg6.apps.googleusercontent.com',
    iosClientId: '884285337726-dlqkrp34vnsa2pj8lpmpo8fgsbo0g8og.apps.googleusercontent.com',
    iosBundleId: 'com.idconexion.cobranzas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2MtantE_FkjVf6Od0cB7N1Z50Ca_lIM0',
    appId: '1:884285337726:ios:6eee20e0f2233697aa682f',
    messagingSenderId: '884285337726',
    projectId: 'gestorcobranza-721b0',
    storageBucket: 'gestorcobranza-721b0.appspot.com',
    androidClientId: '884285337726-c83mr8v19rha29mdjfu1hikdfrcrcbg6.apps.googleusercontent.com',
    iosClientId: '884285337726-dlqkrp34vnsa2pj8lpmpo8fgsbo0g8og.apps.googleusercontent.com',
    iosBundleId: 'com.idconexion.cobranzas',
  );
}
